// NOTE: these strings are looked up VERBATIM (exact match) by
// ocr-service's SCHOOL_STRATEGY_REGISTRY (app/normalization/__init__.py)
// to pick an OCR header-matching strategy and to power the institution-
// mismatch cross-check. If you add/rename a school here, add/rename the
// matching key over there too, or that school silently loses its
// dedicated strategy and drops out of the "which OTHER school is this"
// detection.
export const SCHOOLS = [
    "AMA Computer College",
    "Batangas State University",
    "Calamba Doctors College",
    "Calamba Institute",
    "City College of Calamba",
    "Colegio de San Juan de Letran",
    "Don Bosco College",
    "Laguna Colleges of Business and Arts",
    "Laguna State Polytechnic University",
    "Lyceum of the Philippines",
    "Mapua-Malayan College of Laguna",
    "National University",
    "Our Lady of Assumption College",
    "Pamantasan ng Cabuyao",
    "Polytechnic University of the Philippines",
    "PHINMA Rizal College of Laguna",
    "STI College Calamba",
    "St. Ignatius",
    "St. Michael College of Laguna",
    "St. Vincent College of Cabuyao",
    "Philippine Women's University",
    "University of Perpetual Help System DALTA Calamba",
    "University of Perpetual Help System JONELTA Biñan",
    "University of Perpetual Help Las Piñas",
    "University of the Philippines",
    "University of the Philippines Los Baños",
    "Westbridge Institute of Technology",
    "Our Lady of Fatima University",
    "Saint Benilde International School",
    "San Pedro College",
    "Trimex College of Biñan",
    "STI Santa Rosa",
    "Arellano University",
    "Philippine Merchant Marine School",
    "PNTC College",
    "Saint John and Paul Educational Foundation Inc.",
    "Pamantasan ng Lungsod ng Maynila",
    "Pamantasan ng Lungsod ng Muntinlupa",
    "St. John Colleges",
    "Citi Global Colleges",
    "Philippine Nautical Technology",
    "Far Eastern University",
    "University of Santo Tomas",
];

export const COURSES = [
    "AB Communication",
    "AB English Language Studies",
    "AB History",
    "AB Journalism",
    "AB Political Science",
    "AB Psychology",
    "AB Sociology",
    "BS Accountancy",
    "BS Accounting Information System",
    "BS Agribusiness",
    "BS Agriculture",
    "BS Architecture",
    "BS Biology",
    "BS Business Administration",
    "BS Chemical Engineering",
    "BS Chemistry",
    "BS Civil Engineering",
    "BS Computer Engineering",
    "BS Computer Science",
    "BS Criminology",
    "BS Customs Administration",
    "BS Economics",
    "BS Education",
    "BS Electrical Engineering",
    "BS Electronics Engineering",
    "BS Elementary Education",
    "BS Entrepreneurship",
    "BS Environmental Science",
    "BS Fisheries",
    "BS Food Technology",
    "BS Forestry",
    "BS Hospitality Management",
    "BS Hotel and Restaurant Management",
    "BS Industrial Engineering",
    "BS Information Systems",
    "BS Information Technology",
    "BS Interior Design",
    "BS Legal Management",
    "BS Marine Biology",
    "BS Marine Transportation",
    "BS Marketing Management",
    "BS Mathematics",
    "BS Mechanical Engineering",
    "BS Medical Technology",
    "BS Midwifery",
    "BS Nursing",
    "BS Nutrition and Dietetics",
    "BS Occupational Therapy",
    "BS Pharmacy",
    "BS Physical Therapy",
    "BS Public Administration",
    "BS Radiologic Technology",
    "BS Real Estate Management",
    "BS Secondary Education",
    "BS Social Work",
    "BS Statistics",
    "BS Tourism Management",
    "Other",
];

export const YEAR_LEVELS = ["1st Year", "2nd Year", "3rd Year", "4th Year"];

export function getDocFields(isMinor) {
    return [
        {
            key: "enrollment",
            type: "registration_form",
            label: "Registration Form",
            hint: "Must clearly show your name, school, and school year.",
        },
        {
            key: "schoolId",
            type: "school_id",
            label: "School ID",
            hint: "Must clearly show your name and school name.",
        },
        {
            key: "voters",
            type: "voters_certificate",
            label: isMinor ? "Guardian's Voter's Certificate" : "Voter's Certificate",
            hint: isMinor
                ? "Must clearly show your guardian's name and Barangay Mamatid as your registered barangay."
                : "Must clearly show your name and Barangay Mamatid as your registered barangay.",
        },
    ];
}