export const SCHOOLS = [
    "Pamantasan ng Cabuyao",
    "Mapúa Malayan Colleges Laguna",
    "St. Vincent College of Cabuyao",
    "Our Lady of Assumption College",
    "Colegio de Sto. Niño de Cabuyao",
    "Calamba Doctor's College",
    "STI College Calamba",
    "University of Perpetual Help System DALTA",
    "Colegio de San Juan de Letran Calamba",
    "De La Salle University Canlubang",
    "AMA Computer College Calamba",
    "University of the Philippines Los Baños",
    "Lyceum of the Philippines University Laguna",
    "Laguna College of Business and Arts",
    "Dominican College of Santa Rosa",
    "Polytechnic University of the Philippines",
];

export const COURSES = [
    "AB Communication",
    "AB English Language Studies",
    "AB History",
    "AB Journalism",
    "AB Political Science",
    "AB Psychology",
    "AB Sociology",
    "BS Accountancy",
    "BS Accounting Information System",
    "BS Agribusiness",
    "BS Agriculture",
    "BS Architecture",
    "BS Biology",
    "BS Business Administration",
    "BS Chemical Engineering",
    "BS Chemistry",
    "BS Civil Engineering",
    "BS Computer Engineering",
    "BS Computer Science",
    "BS Criminology",
    "BS Customs Administration",
    "BS Economics",
    "BS Education",
    "BS Electrical Engineering",
    "BS Electronics Engineering",
    "BS Elementary Education",
    "BS Entrepreneurship",
    "BS Environmental Science",
    "BS Fisheries",
    "BS Food Technology",
    "BS Forestry",
    "BS Hospitality Management",
    "BS Hotel and Restaurant Management",
    "BS Industrial Engineering",
    "BS Information Systems",
    "BS Information Technology",
    "BS Interior Design",
    "BS Legal Management",
    "BS Marine Biology",
    "BS Marine Transportation",
    "BS Marketing Management",
    "BS Mathematics",
    "BS Mechanical Engineering",
    "BS Medical Technology",
    "BS Midwifery",
    "BS Nursing",
    "BS Nutrition and Dietetics",
    "BS Occupational Therapy",
    "BS Pharmacy",
    "BS Physical Therapy",
    "BS Public Administration",
    "BS Radiologic Technology",
    "BS Real Estate Management",
    "BS Secondary Education",
    "BS Social Work",
    "BS Statistics",
    "BS Tourism Management",
    "Other",
];

export const YEAR_LEVELS = ["1st Year", "2nd Year", "3rd Year", "4th Year"];

export function getDocFields(isMinor) {
    return [
        {
            key: "enrollment",
            type: "registration_form",
            label: "Registration Form",
            hint: "Must clearly show your name, school, and school year.",
        },
        {
            key: "schoolId",
            type: "school_id",
            label: "School ID",
            hint: "Must clearly show your name and school name.",
        },
        {
            key: "voters",
            type: "voters_certificate",
            label: isMinor ? "Guardian's Voter's Certificate" : "Voter's Certificate",
            hint: isMinor
                ? "Must clearly show your guardian's name and Barangay Mamatid as your registered barangay."
                : "Must clearly show your name and Barangay Mamatid as your registered barangay.",
        },
    ];
}